- name: Copie fichier index.html
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0644
  tags:
    - apache_cod

- name: Copie template index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: 0644
  tags:
    - apache_code